concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Models/Auto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace MVCConcesionaria.Models
{
    public class Auto : Vehiculo
    {

        [DisplayName("Cantidad de puertas")]
        public int CantPuertas { get; set; }

        public Auto()
        {
        }

        public Auto(int ID, string marca, string modelo, Boolean esUsado, double cantKm, int puertas) : base(ID, marca, modelo, esUsado, cantKm)
        {
            this.CantPuertas = puertas;
        }

    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Controllers/AutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using MVCConcesionaria.Context;
using MVCConcesionaria.Models;
using System.IO;
using System.Threading.Tasks;
using System.Diagnostics;

namespace MVCConcesionaria.Controllers
{
    public class AutoController : Controller
    {
        private readonly ConcesionariaDatabaseContext _context;
        private IWebHostEnvironment _environment;

        public AutoController(ConcesionariaDatabaseContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: Auto
        public async Task<IActionResult> Index()
        {
            return View(await _context.Autos.ToListAsync());
        }

        // GET: Auto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var auto = await _context.Autos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (auto == null)
            {
                return NotFound();
            }

            return View(auto);
        }

        // GET: Auto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Auto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( Auto auto)
        {
            if (auto.PhotoAvatar != null && auto.PhotoAvatar.Length > 0)
            {
                auto.ImageMimeType = auto.PhotoAvatar.ContentType;
                auto.ImageName = Path.GetFileName(auto.PhotoAvatar.FileName);
                using (var memoryStream = new MemoryStream())
                {
                auto.PhotoAvatar.CopyTo(memoryStream);
                auto.PhotoFile = memoryStream.ToArray();
                }
                _context.Add(auto);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Auto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var auto = await _context.Autos.FindAsync(id);
            if (auto == null)
            {
                return NotFound();
            }
            return View(auto);
        }

        // POST: Auto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CantPuertas,ID,Marca,Modelo,EsUsado,CantKm,ImageMimeType,ImageName,PhotoFile,Anio,Precio")] Auto auto)
        {
            if (id != auto.ID)
            {
                return NotFound();
            }
                try
                {
                    _context.Update(auto);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AutoExists(auto.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            return RedirectToAction(nameof(Index));
           
        }


        // GET: Auto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var auto = await _context.Autos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (auto == null)
            {
                return NotFound();
            }

            return View(auto);
        }

        // POST: Auto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var auto = await _context.Autos.FindAsync(id);
            _context.Autos.Remove(auto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult GetImage(int id)
        {
            Auto requestedVehiculo = _context.Autos.SingleOrDefault(a => a.ID == id);
            if (requestedVehiculo != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedVehiculo.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedVehiculo.ImageMimeType);
                }
                else
                {
                    if (requestedVehiculo.PhotoFile.Length > 0)
                    {
                        return File(requestedVehiculo.PhotoFile, requestedVehiculo.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
        private bool AutoExists(int id)
        {
            return _context.Autos.Any(e => e.ID == id);
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Controllers/VentaAutoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCConcesionaria.Context;
using MVCConcesionaria.Models;

namespace MVCConcesionaria.Controllers
{
    public class VentaAutoesController : Controller
    {
        private readonly ConcesionariaDatabaseContext _context;

        public VentaAutoesController(ConcesionariaDatabaseContext context)
        {
            _context = context;
        }

        // GET: VentaAutoes
        public async Task<IActionResult> Index()
        {
            List<VentaAuto> lst = new List<VentaAuto>();
            using (_context)
            {
                lst = (from d in _context.VentaAuto
                       select new VentaAuto
                       {
                           Id = d.Id,
                           auto = _context.Autos.SingleOrDefault(a => a.ID == d.Id),
                           cliente = _context.Persona.SingleOrDefault(a => a.PersonaId == d.IdCliente)
                       }).ToList();
            }

            ViewBag.items = lst;
            return View();
        }

        // GET: VentaAutoes/Create
        public IActionResult Create()
        {
            List<Auto> lst = new List<Auto>();
            List<Persona> lstPersona = new List<Persona>();
            using (_context)
            {
                lst = (from d in _context.Autos
                       select new Auto
                       {
                           ID = d.ID,
                           Marca = d.Marca,
                           Modelo = d.Modelo,
                           Precio = d.Precio,
                           Anio = d.Anio
                       }).ToList();
                lstPersona = (from d in _context.Persona
                       select new Persona
                       {
                           PersonaId = d.PersonaId,
                           PersonaDNI = d.PersonaDNI,
                           Apellido = d.Apellido,
                           Nombre = d.Nombre
                       }).ToList();
            }

            List<SelectListItem> items = lst.ConvertAll(d =>
            {
            return new SelectListItem()
            {
                    Text = d.datosVehiculo,
                    Value = d.ID.ToString(),
                    Selected = false
                };
            });
            List<SelectListItem> personas = lstPersona.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.datosPersona,
                    Value = d.PersonaId.ToString(),
                    Selected = false
                };
            });

            ViewBag.items = items;
            ViewBag.personas= personas;
            return View();
        }

        // POST: VentaAutoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVentAuto,IdCliente,Id")] VentaAuto ventaAuto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ventaAuto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ventaAuto);
        }

        
        private bool VentaAutoExists(int id)
        {
            return _context.VentaAuto.Any(e => e.IdVentAuto == id);
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Auto/Create.cshtml
@model MVCConcesionaria.Models.Auto

@{
    ViewData["Title"] = "Create";
}

<h1>Creación</h1>

<h4>Auto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CantPuertas" class="control-label"></label>
                <input asp-for="CantPuertas" class="form-control" />
                <span asp-validation-for="CantPuertas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input id="usado" class="form-check-input" asp-for="EsUsado" /> @Html.DisplayNameFor(model => model.EsUsado)
                </label>
            </div>
            <div id="kms" class="form-group none">
                <label asp-for="CantKm" class="control-label"></label>
                <input asp-for="CantKm" class="form-control" />
                <span asp-validation-for="CantKm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotoAvatar"></label>
                <input asp-for="PhotoAvatar" type="file" />
                <span asp-validation-for="PhotoAvatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Auto/Delete.cshtml
@model MVCConcesionaria.Models.Auto

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Estas seguro que queres editarlo?</h3>
<div>
    <h4>Auto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CantPuertas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CantPuertas)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EsUsado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EsUsado)
        </dd>
        @if (Model.EsUsado == true)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CantKm)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CantKm)
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
    </form>
</div>

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Auto/Details.cshtml
@model MVCConcesionaria.Models.Auto

@{
    ViewData["Title"] = "Details";
}

<h1>Detalle</h1>

<div>
    <h4>Auto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CantPuertas)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CantPuertas)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EsUsado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EsUsado)
        </dd>
        @if (Model.EsUsado == true)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CantKm)
            </dt>

            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CantKm)
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID" class="boton amarillo"><i class="fas fa-pencil-alt"></i></a>
    <a asp-action="Index" class="boton azul"><i class="fas fa-backward"></i></a>
</div>

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Auto/Edit.cshtml
@model MVCConcesionaria.Models.Auto

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Auto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="CantPuertas" class="control-label"></label>
                <input asp-for="CantPuertas" class="form-control" />
                <span asp-validation-for="CantPuertas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input id="usado" class="form-check-input" asp-for="EsUsado" /> @Html.DisplayNameFor(model => model.EsUsado)
                </label>
            </div>
            @if (Model.EsUsado == true)
            {
                <div id="kms" class="form-group">
                    <label asp-for="CantKm" class="control-label"></label>
                    <input asp-for="CantKm" class="form-control" />
                    <span asp-validation-for="CantKm" class="text-danger"></span>
                </div> }
            else
            {
                <div id="kms" class="none form-group">
                    <label asp-for="CantKm" class="control-label"></label>
                    <input asp-for="CantKm" class="form-control" />
                    <span asp-validation-for="CantKm" class="text-danger"></span>
                </div>}
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div>
            <input type="hidden" asp-for="ImageMimeType" />
            <input type="hidden" asp-for="ImageName" />
            <input type="hidden" asp-for="PhotoFile" />
            @Html.HiddenFor(c => c.PhotoAvatar)
            @Html.HiddenFor(c => c.PhotoFile)
        </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Auto/Index.cshtml
@model IEnumerable<MVCConcesionaria.Models.Auto>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de autos</h1>

<p>
    <a asp-action="Create">Agregar un auto</a>
</p>
<p>
    <a asp-controller="VentaAutoes" asp-action="Index">Lista de autos vendidos</a>
</p>
<p>
    <a asp-controller="VentaAutoes" asp-action="Create">Vender auto</a>
</p>
<div class="img-container" img-container">
    @foreach (var item in Model)
    {
        <div class="photo-index-card">
            @if (item.ImageName != null)
            {
                <div class="photo-display">
                    <img class="photo-display-img" src="@Url.Action("GetImage", "Auto", new { Id = item.ID })" />
                </div>}
        <div>
            <p class="display-label">
                Cantidad de puertas: @Html.DisplayFor(model => item.CantPuertas)
            </p>
            <p class="display-label">
                Marca: @Html.DisplayFor(model => item.Marca)
            </p>
            <p class="display-label">
                Modelo: @Html.DisplayFor(model => item.Modelo)
            </p>
            <p class="display-label">
                Anio: @Html.DisplayFor(model => item.Anio)
            </p>
            <p class="display-label">
                Precio: $@Html.DisplayFor(model => item.Precio)
            </p>
            @if (item.EsUsado)
            {
        <p class="display-label">Usado: @Html.DisplayFor(model => item.CantKm)km</p> }
                        else
                        {
        <p class="display-label">Nuevo</p>                }
        </div>
            <div class="contender">
                <a asp-action="Edit" asp-route-id="@item.ID" class="boton amarillo"><i class="fas fa-pencil-alt"></i></a>
                <a asp-action="Details" asp-route-id="@item.ID" class="boton verde "><i class="fas fa-info-circle"></i></a>
                <a asp-action="Delete" asp-route-id="@item.ID" class="boton rojo"><i class="fas fa-trash-alt"></i></a>
            </div>
        </div>}
</div>