concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Models/Moto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace MVCConcesionaria.Models
{
    public class Moto : Vehiculo
    {
        [EnumDataType(typeof(TipoMoto))]
        public TipoMoto Tipo { get; set; }
        public Moto()
        {

        }

        public Moto(int ID, string Marca, string Modelo, Boolean EsUsado, double CantKm, TipoMoto Tipo) : base(ID, Marca, Modelo, EsUsado, CantKm)
        {
            this.Tipo = Tipo;
        }

    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Controllers/MotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using MVCConcesionaria.Context;
using MVCConcesionaria.Models;
using System.IO;
using System.Threading.Tasks;
using System.Diagnostics;

namespace MVCConcesionaria.Controllers
{
    public class MotoController : Controller
    {
        private readonly ConcesionariaDatabaseContext _context;
        private IWebHostEnvironment _environment;

        public MotoController(ConcesionariaDatabaseContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: Moto
        public async Task<IActionResult> Index()
        {
            return View(await _context.Motos.ToListAsync());
        }

        // GET: Moto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moto = await _context.Motos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (moto == null)
            {
                return NotFound();
            }

            return View(moto);
        }

        // GET: Moto/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Moto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Moto moto)
        {
           
            if (moto.PhotoAvatar != null && moto.PhotoAvatar.Length > 0)
            {
                moto.ImageMimeType = moto.PhotoAvatar.ContentType;
                moto.ImageName = Path.GetFileName(moto.PhotoAvatar.FileName);
                using (var memoryStream = new MemoryStream())
                {
                    moto.PhotoAvatar.CopyTo(memoryStream);
                    moto.PhotoFile = memoryStream.ToArray();
                }
                _context.Add(moto);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Moto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moto = await _context.Motos.FindAsync(id);
            if (moto == null)
            {
                return NotFound();
            }
            return View(moto);
        }

        // POST: Moto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Tipo,ID,Marca,Modelo,EsUsado,CantKm,ImageMimeType,ImageName,PhotoFile,Anio,Precio")] Moto moto)
        {
            if (id != moto.ID)
            {
                return NotFound();
            }
            try
            {
                _context.Update(moto);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MotoExists(moto.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Moto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var moto = await _context.Motos
                .FirstOrDefaultAsync(m => m.ID == id);
            if (moto == null)
            {
                return NotFound();
            }

            return View(moto);
        }

        // POST: Moto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var moto = await _context.Motos.FindAsync(id);
            _context.Motos.Remove(moto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult GetImage(int id)
        {
            Moto requestedVehiculo = _context.Motos.SingleOrDefault(c => c.ID == id);
            if (requestedVehiculo != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedVehiculo.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedVehiculo.ImageMimeType);
                }
                else
                {
                    if (requestedVehiculo.PhotoFile.Length > 0)
                    {
                        return File(requestedVehiculo.PhotoFile, requestedVehiculo.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
        private bool MotoExists(int id)
        {
            return _context.Motos.Any(e => e.ID == id);
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Controllers/VentaMotoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCConcesionaria.Context;
using MVCConcesionaria.Models;

namespace MVCConcesionaria.Controllers
{
    public class VentaMotoesController : Controller
    {
        private readonly ConcesionariaDatabaseContext _context;

        public VentaMotoesController(ConcesionariaDatabaseContext context)
        {
            _context = context;
        }

        // GET: VentaMotoes
        public async Task<IActionResult> Index()
        {
            List<VentaMoto> lst = new List<VentaMoto>();
            using (_context)
            {
                lst = (from d in _context.VentaMoto
                       select new VentaMoto
                       {
                           Id = d.Id,
                           moto = _context.Motos.SingleOrDefault(a => a.ID == d.Id),
                           cliente = _context.Persona.SingleOrDefault(a => a.PersonaId == d.IdCliente)
                       }).ToList();
            }

            ViewBag.items = lst;
            return View();
        }

        // GET: VentaMotoes/Create
        public IActionResult Create()
        {
            List<Moto> lst = new List<Moto>();
            List<Persona> lstPersona = new List<Persona>();
            using (_context)
            {
                lst = (from d in _context.Motos
                       select new Moto
                       {
                           ID = d.ID,
                           Marca = d.Marca,
                           Modelo = d.Modelo,
                           Precio = d.Precio,
                           Anio = d.Anio
                       }).ToList();
                lstPersona = (from d in _context.Persona
                              select new Persona
                              {
                                  PersonaId = d.PersonaId,
                                  PersonaDNI = d.PersonaDNI,
                                  Apellido = d.Apellido,
                                  Nombre = d.Nombre
                              }).ToList();
            }

            List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.datosVehiculo,
                    Value = d.ID.ToString(),
                    Selected = false
                };
            });
            List<SelectListItem> personas = lstPersona.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.datosPersona,
                    Value = d.PersonaId.ToString(),
                    Selected = false
                };
            });

            ViewBag.items = items;
            ViewBag.personas = personas;
            return View();
        }

        // POST: VentaMotoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVentaMoto,IdCliente,Id")] VentaMoto ventaMoto)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ventaMoto);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ventaMoto);
        }

        private bool VentaMotoExists(int id)
        {
            return _context.VentaMoto.Any(e => e.IdVentaMoto == id);
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Moto/Create.cshtml
@model MVCConcesionaria.Models.Moto

@{
    ViewData["Title"] = "Create";
}

<h1>Creación</h1>

<h4>Moto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control" asp-items="Html.GetEnumSelectList<TipoMoto>()">

                    <option selected="selected" value="">Seleccione un tipo de moto</option>
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input id="usado" class="form-check-input" asp-for="EsUsado" /> @Html.DisplayNameFor(model => model.EsUsado)
                </label>
            </div>
            <div id="kms" class="form-group none">
                <label asp-for="CantKm" class="control-label"></label>
                <input asp-for="CantKm" class="form-control" />
                <span asp-validation-for="CantKm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-field">
                <label asp-for="PhotoAvatar"></label>
                <input asp-for="PhotoAvatar" type="file" />
                <span asp-validation-for="PhotoAvatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Moto/Delete.cshtml
@model MVCConcesionaria.Models.Moto

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Estas seguro que queres editarlo?</h3>
<div>
    <h4>Moto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EsUsado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EsUsado)
        </dd>
        @if (Model.EsUsado == true)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CantKm)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CantKm)
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
    </form>
</div>

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Moto/Details.cshtml
@model MVCConcesionaria.Models.Moto

@{
    ViewData["Title"] = "Details";
}

<h1>Detalle</h1>

<div>
    <h4>Moto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EsUsado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EsUsado)
        </dd>
        @if (Model.EsUsado == true)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CantKm)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CantKm)
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID" class="boton amarillo"><i class="fas fa-pencil-alt"></i></a>
    <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
</div>

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Moto/Edit.cshtml
@model MVCConcesionaria.Models.Moto

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Moto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <select asp-for="Tipo" class="form-control" asp-items="Html.GetEnumSelectList<TipoMoto>()">
                    <option selected="selected" value="">Seleccione un tipo de moto</option>
                </select>
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input id="usado" class="form-check-input" asp-for="EsUsado" /> @Html.DisplayNameFor(model => model.EsUsado)
                </label>
            </div>
            @if (Model.EsUsado == true)
            {
                <div id="kms" class="form-group">
                    <label asp-for="CantKm" class="control-label"></label>
                    <input asp-for="CantKm" class="form-control" />
                    <span asp-validation-for="CantKm" class="text-danger"></span>
                </div> }
            else
            {
                <div id="kms" class="none form-group">
                    <label asp-for="CantKm" class="control-label"></label>
                    <input asp-for="CantKm" class="form-control" />
                    <span asp-validation-for="CantKm" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div>
                <input type="hidden" asp-for="ImageMimeType" />
                <input type="hidden" asp-for="ImageName" />
                <input type="hidden" asp-for="PhotoFile" />
                @Html.HiddenFor(m => m.PhotoAvatar)
                @Html.HiddenFor(m => m.PhotoFile)
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Moto/Index.cshtml
@model IEnumerable<MVCConcesionaria.Models.Moto>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Motos</h1>

<p>
    <a asp-action="Create">Agregar una Moto</a>
</p>
<p>
    <a asp-controller="VentaMotoes" asp-action="Index">Lista de moto vendidos</a>
</p>
<p>
    <a asp-controller="VentaMotoes" asp-action="Create">Vender moto</a>
</p>
<div class="img-container" img-container">
    @foreach (var item in Model)
    {
        <div class="photo-index-card">
            @if (item.ImageName != null)
            {
                <div class="photo-display">
                    <img class="photo-display-img" src="@Url.Action("GetImage", "Moto", new { Id = item.ID })" />
                </div>}
        <div>
            <p class="display-label">
                Tipo: @Html.DisplayFor(model => item.Tipo)
            </p>
            <p class="display-label">
                Marca: @Html.DisplayFor(model => item.Marca)
            </p>
            <p class="display-label">
                Modelo: @Html.DisplayFor(model => item.Modelo)
            </p>
            <p class="display-label">
                Anio: @Html.DisplayFor(model => item.Anio)
            </p>
            <p class="display-label">
                Precio: $@Html.DisplayFor(model => item.Precio)
            </p>
            @if (item.EsUsado)
            {
        <p class="display-label">Usado: @Html.DisplayFor(model => item.CantKm)km</p> }
    else
    {
        <p class="display-label">Nuevo</p>}
        </div>
            <div class="contender">
                <a asp-action="Edit" asp-route-id="@item.ID" class="boton amarillo"><i class="fas fa-pencil-alt"></i></a> 
                <a asp-action="Details" asp-route-id="@item.ID" class="boton verde "><i class="fas fa-info-circle"></i></a> 
                <a asp-action="Delete" asp-route-id="@item.ID" class="boton rojo"><i class="fas fa-trash-alt"></i></a>
            </div>
        </div>}
</div>
 