concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Models/Camioneta.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace MVCConcesionaria.Models
{
    public class Camioneta : Vehiculo
    {
        [DisplayName("Es 4x4")]
        public Boolean Es4x4 { get; set; }

        [DisplayName("Es doble cabina")]
        public Boolean EsDobleCabina { get; set; }

        public Camioneta()
        {

        }

        public Camioneta(int ID, string marca, string modelo, Boolean esUsado, double cantKm, Boolean es4x4, Boolean dobleCab) : base(ID, marca, modelo, esUsado, cantKm)
        {
            this.Es4x4 = es4x4;
            this.EsDobleCabina = dobleCab;
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Controllers/CamionetaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using MVCConcesionaria.Context;
using MVCConcesionaria.Models;
using System.IO;
using System.Threading.Tasks;
using System.Diagnostics;

namespace MVCConcesionaria.Controllers
{
    public class CamionetaController : Controller
    {
        private readonly ConcesionariaDatabaseContext _context;
        private IWebHostEnvironment _environment;

        public CamionetaController(ConcesionariaDatabaseContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        // GET: Camioneta
        public async Task<IActionResult> Index()
        {
            return View(await _context.Camionetas.ToListAsync());
        }

        // GET: Camioneta/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camioneta = await _context.Camionetas
                .FirstOrDefaultAsync(m => m.ID == id);
            if (camioneta == null)
            {
                return NotFound();
            }

            return View(camioneta);
        }

        // GET: Camioneta/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Camioneta/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Camioneta camioneta)
        {
            if (camioneta.PhotoAvatar != null && camioneta.PhotoAvatar.Length > 0)
            {
                camioneta.ImageMimeType = camioneta.PhotoAvatar.ContentType;
                camioneta.ImageName = Path.GetFileName(camioneta.PhotoAvatar.FileName);
                using (var memoryStream = new MemoryStream())
                {
                    camioneta.PhotoAvatar.CopyTo(memoryStream);
                    camioneta.PhotoFile = memoryStream.ToArray();
                }
                _context.Add(camioneta);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Camioneta/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camioneta = await _context.Camionetas.FindAsync(id);
            if (camioneta == null)
            {
                return NotFound();
            }
            return View(camioneta);
        }

        // POST: Camioneta/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Es4x4,EsDobleCabina,ID,Marca,Modelo,EsUsado,CantKm,ImageMimeType,ImageName,PhotoFile,Anio,Precio")] Camioneta camioneta)
        {
            if (id != camioneta.ID)
            {
                return NotFound();

            }
            try
            {
                _context.Update(camioneta);
                _context.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CamionetaExists(camioneta.ID))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Camioneta/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camioneta = await _context.Camionetas
                .FirstOrDefaultAsync(m => m.ID == id);
            if (camioneta == null)
            {
                return NotFound();
            }

            return View(camioneta);
        }

        // POST: Camioneta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var camioneta = await _context.Camionetas.FindAsync(id);
            _context.Camionetas.Remove(camioneta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult GetImage(int id)
        {
            Camioneta requestedVehiculo = _context.Camionetas.SingleOrDefault(a => a.ID == id);
            if (requestedVehiculo != null)
            {
                string webRootpath = _environment.WebRootPath;
                string folderPath = "\\images\\";
                string fullPath = webRootpath + folderPath + requestedVehiculo.ImageName;
                if (System.IO.File.Exists(fullPath))
                {
                    FileStream fileOnDisk = new FileStream(fullPath, FileMode.Open);
                    byte[] fileBytes;
                    using (BinaryReader br = new BinaryReader(fileOnDisk))
                    {
                        fileBytes = br.ReadBytes((int)fileOnDisk.Length);
                    }
                    return File(fileBytes, requestedVehiculo.ImageMimeType);
                }
                else
                {
                    if (requestedVehiculo.PhotoFile.Length > 0)
                    {
                        return File(requestedVehiculo.PhotoFile, requestedVehiculo.ImageMimeType);
                    }
                    else
                    {
                        return NotFound();
                    }
                }
            }
            else
            {
                return NotFound();
            }
        }
        private bool CamionetaExists(int id)
        {
            return _context.Camionetas.Any(e => e.ID == id);
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Controllers/VentaCamionetasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCConcesionaria.Context;
using MVCConcesionaria.Models;

namespace MVCConcesionaria.Controllers
{
    public class VentaCamionetasController : Controller
    {
        private readonly ConcesionariaDatabaseContext _context;

        public VentaCamionetasController(ConcesionariaDatabaseContext context)
        {
            _context = context;
        }

        // GET: VentaCamionetas
        public async Task<IActionResult> Index()
        {
            List<VentaCamioneta> lst = new List<VentaCamioneta>();
            using (_context)
            {
                lst = (from d in _context.VentaCamioneta
                       select new VentaCamioneta
                       {
                           Id = d.Id,
                           camioneta = _context.Camionetas.SingleOrDefault(a => a.ID == d.Id),
                           cliente = _context.Persona.SingleOrDefault(a => a.PersonaId == d.IdCliente)
                       }).ToList();
            }

            ViewBag.items = lst;
            return View();
        }

        
        // GET: VentaCamionetas/Create
        public IActionResult Create()
        {
            List<Camioneta> lst = new List<Camioneta>();
            List<Persona> lstPersona = new List<Persona>();
            using (_context)
            {
                lst = (from d in _context.Camionetas
                       select new Camioneta
                       {
                           ID = d.ID,
                           Marca = d.Marca,
                           Modelo = d.Modelo,
                           Precio = d.Precio,
                           Anio = d.Anio
                       }).ToList();
                lstPersona = (from d in _context.Persona
                              select new Persona
                              {
                                  PersonaId = d.PersonaId,
                                  PersonaDNI = d.PersonaDNI,
                                  Apellido = d.Apellido,
                                  Nombre = d.Nombre
                              }).ToList();
            }

            List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.datosVehiculo,
                    Value = d.ID.ToString(),
                    Selected = false
                };
            });
            List<SelectListItem> personas = lstPersona.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.datosPersona,
                    Value = d.PersonaId.ToString(),
                    Selected = false
                };
            });

            ViewBag.items = items;
            ViewBag.personas = personas;
            return View();
        }

        // POST: VentaCamionetas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdVentaCamioneta,IdCliente,Id")] VentaCamioneta ventaCamioneta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ventaCamioneta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ventaCamioneta);
        }

     
        private bool VentaCamionetaExists(int id)
        {
            return _context.VentaCamioneta.Any(e => e.IdVentaCamioneta == id);
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Camioneta/Create.cshtml
@model MVCConcesionaria.Models.Camioneta

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Camioneta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Es4x4" /> @Html.DisplayNameFor(model => model.Es4x4)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EsDobleCabina" /> @Html.DisplayNameFor(model => model.EsDobleCabina)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input id="usado" class="form-check-input" asp-for="EsUsado" /> @Html.DisplayNameFor(model => model.EsUsado)
                </label>
            </div>
            <div id="kms" class="form-group none">
                <label asp-for="CantKm" class="control-label"></label>
                <input asp-for="CantKm" class="form-control" />
                <span asp-validation-for="CantKm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div class="form-field">
                <label asp-for="PhotoAvatar"></label>
                <input asp-for="PhotoAvatar" type="file" />
                <span asp-validation-for="PhotoAvatar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Camioneta/Delete.cshtml
@model MVCConcesionaria.Models.Camioneta

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Estas seguro que queres editarlo?</h3>
<div>
    <h4>Camioneta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Es4x4)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Es4x4)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EsDobleCabina)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EsDobleCabina)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EsUsado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EsUsado)
        </dd>
        @if (Model.EsUsado == true)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CantKm)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CantKm)
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Eliminar" class="btn btn-danger" />
        <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
    </form>
</div>

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Camioneta/Details.cshtml
@model MVCConcesionaria.Models.Camioneta

@{
    ViewData["Title"] = "Details";
}

<h1>Detalle</h1>

<div>
    <h4>Camioneta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Es4x4)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Es4x4)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EsDobleCabina)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EsDobleCabina)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EsUsado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EsUsado)
        </dd>
        @if (Model.EsUsado == true)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CantKm)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CantKm)
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Anio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Anio)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID" class="boton amarillo"><i class="fas fa-pencil-alt"></i></a>
    <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
</div>

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Camioneta/Edit.cshtml
@model MVCConcesionaria.Models.Camioneta

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Camioneta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Es4x4" /> @Html.DisplayNameFor(model => model.Es4x4)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EsDobleCabina" /> @Html.DisplayNameFor(model => model.EsDobleCabina)
                </label>
            </div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input id="usado" class="form-check-input" asp-for="EsUsado" /> @Html.DisplayNameFor(model => model.EsUsado)
                </label>
            </div>
            @if (Model.EsUsado == true)
            {
                <div id="kms" class="form-group">
                    <label asp-for="CantKm" class="control-label"></label>
                    <input asp-for="CantKm" class="form-control" />
                    <span asp-validation-for="CantKm" class="text-danger"></span>
                </div> }
            else
            {
                <div id="kms" class="none form-group">
                    <label asp-for="CantKm" class="control-label"></label>
                    <input asp-for="CantKm" class="form-control" />
                    <span asp-validation-for="CantKm" class="text-danger"></span>
                </div>}
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Anio" class="control-label"></label>
                <input asp-for="Anio" class="form-control" />
                <span asp-validation-for="Anio" class="text-danger"></span>
            </div>
            <div>
                <input type="hidden" asp-for="ImageMimeType" />
                <input type="hidden" asp-for="ImageName" />
                <input type="hidden" asp-for="PhotoFile" />
                @Html.HiddenFor(c => c.PhotoAvatar)
                @Html.HiddenFor(c => c.PhotoFile)
            </div>
            <div class="form-group">
                <input type="submit" value="Guadrar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="boton asul"><i class="fas fa-backward"></i></a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Camioneta/Index.cshtml
@model IEnumerable<MVCConcesionaria.Models.Camioneta>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de camionetas</h1>

<p>
    <a asp-action="Create">Agregar una camioneta</a>
</p>
<p>
    <a asp-controller="VentaCamionetas" asp-action="Index">Lista de camionetas vendidas</a>
</p>
<p>
    <a asp-controller="VentaCamionetas" asp-action="Create">Vender camioneta</a>
</p>

   

<div class="img-container" img-container">
    @foreach (var item in Model)
    {
        <div class="photo-index-card">
            @if (item.ImageName != null)
            {
                <div class="photo-display">
                    <img class="photo-display-img" src="@Url.Action("GetImage", "Camioneta", new { Id = item.ID })" />
                </div>}
        <div>
            <p class="display-label">
                Marca: @Html.DisplayFor(model => item.Marca)
            </p>
            <p class="display-label">
                Modelo: @Html.DisplayFor(model => item.Modelo)
            </p>
            <p class="display-label">
                Anio: @Html.DisplayFor(model => item.Anio)
            </p>
            <p class="display-label">
                Precio: $@Html.DisplayFor(model => item.Precio)
            </p>
            @if (item.EsUsado)
            {
        <p class="display-label">Usado: @Html.DisplayFor(model => item.CantKm)km</p> }
                        else
                        {
        <p class="display-label">Nuevo</p>}
            @if (item.Es4x4)
            {
        <p class="display-label">4X4</p>}
            @if (item.EsDobleCabina)
            {
        <p class="display-label">Doble cabina</p>}

        </div>
            <div class="contender">
                <a asp-action="Edit" asp-route-id="@item.ID" class="boton amarillo"><i class="fas fa-pencil-alt"></i></a>
                <a asp-action="Details" asp-route-id="@item.ID" class="boton verde "><i class="fas fa-info-circle"></i></a>
                <a asp-action="Delete" asp-route-id="@item.ID" class="boton rojo"><i class="fas fa-trash-alt"></i></a>
            </div>
        </div>}
</div>