concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Models/Persona.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace MVCConcesionaria.Models
{
    public class Persona
    {


        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int PersonaId { get; set; }

        [Required(ErrorMessage = "Se debe cargar el dni")]
        [DisplayName("DNI")]
        public int PersonaDNI { get; set; }

        [Required(ErrorMessage = "Se debe cargar el nombre")]
        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Se debe cargar el apellido")]
        [DisplayName("Apellido")]
        public string Apellido { get; set; }

        [NotMapped]
        public String datosPersona {
            get {
                return Nombre + " - " + Apellido + " - " + PersonaDNI;
                } 
        }
        public Persona()
        {

        }

        public Persona(string n, string a, int d)
        {
            Nombre = n;
            Apellido = a;
            PersonaDNI = d;
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCConcesionaria.Context;
using MVCConcesionaria.Models;

namespace MVCConcesionaria.Controllers
{
    public class PersonasController : Controller
    {
        private readonly ConcesionariaDatabaseContext _context;

        public PersonasController(ConcesionariaDatabaseContext context)
        {
            _context = context;
        }

        // GET: Personas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Persona.ToListAsync());
        }

        // GET: Personas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Persona
                .FirstOrDefaultAsync(m => m.PersonaId == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // GET: Personas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Personas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonaId,PersonaDNI,Nombre,Apellido")] Persona persona)
        {
            if (ModelState.IsValid)
            {
                _context.Add(persona);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Persona.FindAsync(id);
            if (persona == null)
            {
                return NotFound();
            }
            return View(persona);
        }

        // POST: Personas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PersonaId,PersonaDNI,Nombre,Apellido")] Persona persona)
        {
            if (id != persona.PersonaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(persona);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PersonaExists(persona.PersonaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(persona);
        }

        // GET: Personas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var persona = await _context.Persona
                .FirstOrDefaultAsync(m => m.PersonaId == id);
            if (persona == null)
            {
                return NotFound();
            }

            return View(persona);
        }

        // POST: Personas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var persona = await _context.Persona.FindAsync(id);
            _context.Persona.Remove(persona);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonaExists(int id)
        {
            return _context.Persona.Any(e => e.PersonaId == id);
        }
    }
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Personas/Create.cshtml
@model MVCConcesionaria.Models.Persona

@{
    ViewData["Title"] = "Create";
}

<h1>Nuevo cliente</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PersonaDNI" class="control-label"></label>
                <input asp-for="PersonaDNI" class="form-control" />
                <span asp-validation-for="PersonaDNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a lista de clientes</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Personas/Delete.cshtml
@model MVCConcesionaria.Models.Persona

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar cliente</h1>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonaDNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonaDNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PersonaId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="nav-link text-dark" asp-area="" asp-controller="Personas" asp-action="Index"></a>
        <a asp-action="Index">Volver a lista de clientes</a>
    </form>
</div>

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Personas/Details.cshtml
@model MVCConcesionaria.Models.Persona

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles del cliente</h1>

<div>
    <h4>Persona</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonaDNI)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonaDNI)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PersonaId">Editar</a> |
    <a asp-action="Index">Volver a lista de clientes</a>
</div>

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Personas/Edit.cshtml
@model MVCConcesionaria.Models.Persona

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar cliente</h1>

<h4>Persona</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PersonaId" />
            <div class="form-group">
                <label asp-for="PersonaDNI" class="control-label"></label>
                <input asp-for="PersonaDNI" class="form-control" />
                <span asp-validation-for="PersonaDNI" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apellido" class="control-label"></label>
                <input asp-for="Apellido" class="form-control" />
                <span asp-validation-for="Apellido" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver a lista de clientes</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

concesionaria_v2/MVC-CONCESIONARIA/MVCConcesionaria/MVCConcesionaria/Views/Personas/Index.cshtml
@model IEnumerable<MVCConcesionaria.Models.Persona>

@{
    ViewData["Title"] = "Index";
}

<h1>Clientes</h1>

<p>
    <a asp-action="Create">Crear nuevo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PersonaDNI)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PersonaDNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PersonaId" class="boton amarillo"><i class="fas fa-pencil-alt"></i></a>
                <a asp-action="Details" asp-route-id="@item.PersonaId" class="boton verde "><i class="fas fa-info-circle"></i></a>
                <a asp-action="Delete" asp-route-id="@item.PersonaId" class="boton rojo"><i class="fas fa-trash-alt"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>